<?php

namespace AppBundle\Repository;

/**
 * ProjectPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
